//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public byte[] password { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int usertypeid { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
